"""Hatch build hook: bake the git commit count into the wheel.

The relay's runtime version is meant to bump on every commit, but a wheel
install doesn't ship `.git`, so a runtime `git rev-list` from inside the
package always fails and the hardcoded fallback "wins". Solving it from the
source side instead: at build time (where `.git` is still present in the
checkout uvx clones) we compute the commit count and write it to
`branch_monkey_mcp/_version.py`. The runtime imports that file first and
only falls back to the runtime git lookup when the file is absent (e.g. a
pip install -e from a working tree without going through the build).
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class VersionWriter(BuildHookInterface):
    PLUGIN_NAME = "version-writer"

    def initialize(self, version, build_data):
        root = Path(self.root)
        out_path = root / "branch_monkey_mcp" / "_version.py"
        # Best-effort: only overwrite when git is available AND returns a
        # higher count than what's already on disk. uv's build isolation
        # may strip .git, so we'd otherwise clobber the committed fallback
        # with "0". Keeping the larger value gives us correctness in both
        # paths: from-source builds bump it, isolated builds preserve it.
        existing = self._read_existing(out_path)
        existing_sha = self._read_existing_sha(out_path)
        try:
            result = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"],
                cwd=str(root),
                capture_output=True,
                text=True,
                check=True,
                timeout=5,
            )
            count_from_git = result.stdout.strip()
        except Exception:
            count_from_git = ""

        try:
            sha_result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=str(root),
                capture_output=True,
                text=True,
                check=True,
                timeout=5,
            )
            sha_from_git = sha_result.stdout.strip()
        except Exception:
            sha_from_git = ""

        try:
            git_int = int(count_from_git) if count_from_git else 0
            existing_int = int(existing) if existing else 0
        except ValueError:
            git_int, existing_int = 0, 0

        final = str(max(git_int, existing_int)) if max(git_int, existing_int) > 0 else (existing or "0")
        final_sha = sha_from_git or existing_sha or ""

        out_path.write_text(
            "# Auto-generated by hatch_build.VersionWriter — committed so wheel\n"
            "# builds without access to .git still ship a real version number.\n"
            f'COMMIT_COUNT = "{final}"\n'
            f'COMMIT_SHA = "{final_sha}"\n'
        )

    @staticmethod
    def _read_existing_sha(path: Path) -> str:
        try:
            text = path.read_text()
        except Exception:
            return ""
        for line in text.splitlines():
            line = line.strip()
            if line.startswith("COMMIT_SHA"):
                _, _, rhs = line.partition("=")
                return rhs.strip().strip('"').strip("'")
        return ""

    @staticmethod
    def _read_existing(path: Path) -> str:
        try:
            text = path.read_text()
        except Exception:
            return ""
        for line in text.splitlines():
            line = line.strip()
            if line.startswith("COMMIT_COUNT"):
                # COMMIT_COUNT = "287"
                _, _, rhs = line.partition("=")
                return rhs.strip().strip('"').strip("'")
        return ""
