# Auto-generated by hatch_build.VersionWriter — committed so wheel
# builds without access to .git still ship a real version number.
COMMIT_COUNT = "299"
COMMIT_SHA = "4de5c54000000000000000000000000000000000"
