# Auto-generated by hatch_build.VersionWriter — committed so wheel
# builds without access to .git still ship a real version number.
COMMIT_COUNT = "298"
COMMIT_SHA = "f1ee609ab085d81a7c7e0f4b951f2ad636577db6"
